name: Sync AI Rules
on:
  # schedule:
  #   - cron: '0 0 1 * *' # Monthly
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Download remote file
        run: |
          curl -sL https://raw.githubusercontent.com/HugoRCD/nuxt-ui-rules/refs/heads/main/rules/nuxt-ui.md --output nuxt-ui.md
      - name: Compare and commit if changed
        run: |
          if ! cmp -s nuxt-ui.md .prompts/nuxt-ui.md; then
            mv nuxt-ui.md .prompts/nuxt-ui.md
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add .prompts/nuxt-ui.md
            git commit -m "chore(ci): synced nuxt-ui.md"
            git push
          else
            echo "No changes detected."
          fi
